In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
b = np.array([4,5,6])
a * b

array([ 4, 10, 18])

In [3]:
a[0]

1

In [5]:
a = np.arange(10)

In [6]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
a[1:-3]

array([1, 2, 3, 4, 5, 6])

In [8]:
a[1:6:2]

array([1, 3, 5])

In [10]:
a = np.arange(36)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [11]:
b = a.reshape(6,6)
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [12]:
b[0, 3:5]

array([3, 4])

In [14]:
b[:,2]#third column

array([ 2,  8, 14, 20, 26, 32])

In [16]:
b[:,2:3]

array([[ 2],
       [ 8],
       [14],
       [20],
       [26],
       [32]])

In [17]:
b[4:,4:]

array([[28, 29],
       [34, 35]])

In [18]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [20]:
c = a[1,2]
c

IndexError: too many indices for array